[package]
name = "dream-chain"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny_http = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4"
md5 = "0.7"
